config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes
  authenticated :user do
    root 'notes#index', as: 'authenticated_root'
  end
  root 'welcome#index'
end

app/models/note.rb
class Note < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes ,:dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :find_note, only: [:show, :edit, :update, :destroy]
  def index
    #@notes  = Note.all.order("created_at DESC")
    #@notes  = Note.where(user_id: current_user)
    @notes  = Note.where("user_id = ? OR privado = ?",current_user, false)
  end
  def show

  end
  def new
    @note = current_user.notes.build
  end
  def create
    @note = current_user.notes.build(note_params)
    if  @note.save
       redirect_to @note
    else
      render 'new'
    end
  end
  def edit

  end
  def update
    if @note.update(note_params)
      redirect_to @note
    else
      render 'edit'
    end
  end
  def destroy
    @note.destroy
    redirect_to notes_path
  end

  private
  def find_note
    @note  =  Note.find(params[:id])
  end
  def note_params
    params.require(:note).permit(:titulo,:contenido,:privado)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>NotasApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
</head>

<body>
  <header>
    <div class='header_inner'><nav>
      <%if user_signed_in? %>
          <%=link_to "Nueva nota", new_note_path%>
					<%=link_to "Salir", destroy_user_session_path, method: :delete%>
      <%else%>
          <%=link_to "Iniciar sesión", new_user_session_path%>
      <%end%>
    </nav></div>
  </header>
  <p class="notice">
    <% if notice %>
    ok noticia
    <%end%>

  </p>
  <p class="alert">
    <% if alert %>
    ok Alerta
    <%end%>
  </p>
  <%= yield %>

</body>

</html>

app/views/notes/_form.html.erb
<%=simple_form_for @note do |f| %>
  <%=f.input :titulo%>
  <%= f.input :contenido%>
  <%= f.input :privado%>
  <%= f.button :submit %>
<%end%>

app/views/notes/edit.html.erb
<h1>Editar Nota</h1>
<%=render 'form'%>
<%=link_to 'Cancelar',note_path%>

app/views/notes/index.html.erb
<div class='wrapper_with_padding'>
  <div class='clearfix' id='notes'>
    <%unless @notes.blank?%>
      <%@notes.each do |note|%>
        <a href="<%=(url_for [note])%>">
        <div class='note'>
          <p class='title'><%=note.titulo %></p>
          <p class='date'><%=note.user.nil? ? 'Anonimo' :  (note.user.email == current_user.email ? 'Tu' : note.user.email)%></p>
        </div>
        </a>
      <%end%>
    <%else%>
      <h2>Agregar Nota</h2>
      <p>
        Parece que no hay notas ... deberias de crear una
      </p>
      <button type="button" name="button"><%= link_to "Nueva Nota", new_note_path %></button>
    <%end%>
  </div>
</div>

app/views/notes/new.html.erb
<h1>Agregar Nota</h1>
<%=render 'form'%>

app/views/notes/show.html.erb
<h1><%=@note.titulo%></h1>
<p><%=@note.contenido%></p>
<span><%= @note.privado%></span>
<%=link_to "Todas las Notas", notes_path%>
<%=link_to "Editar", edit_note_path(@note)%>
<%=link_to "Borrar", note_path(@note),method: :delete, data: {confirm: "Confirmar?"}%>

app/views/welcome/index.html.erb
<div id='banner'>
  <div class='banner_content'>
    <h1>NotasApp</h1>
    <p>
      NoteBook online 100% en Rails
    </p>

      <%=link_to '<button type="button" name="button">Crear Cuenta</button>'.html_safe, new_user_registration_path%>

  </div>
</div>
<div id='testimonial'>
  <div class='wrapper'>
    <p class='quote'>"Una Nueva Manera de Compartir notas"</p>
    <p class='name'>- Mario Vizcaino</p>
  </div>
</div>
<div id='callouts'>
  <div class='callout_inner'>
    <div class='wrapper'>
      <div class='callout'>
        <h2>Notes</h2>
        <p>Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.</p>
      </div>
      <div class='callout'>
        <h2>Notes</h2>
        <p>Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.</p>
      </div>
      <div class='callout'>
        <h2>Notes</h2>
        <p>Viral Echo Park Intelligentsia tattooed, craft beer organic authentic polaroid tousled mlkshk church-key. Fanny pack Banksy vegan  authentic Helvetica.</p>
      </div>
    </div>
  </div>
</div>
<div id='bottom_cta'>
  <div class='wrapper'>
    <h2>Enserio!</h2>
    <p>Crea una Cuenta.. es Gratis!</p>
    <%=link_to '<button type="button" name="button">Dame cliiick!!!</button>'.html_safe, new_user_registration_path%>
  </div>
</div>
<footer>
  <p>&copy; Mario Vizcaino</p>
</footer>